on/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    #url(r'^$', 'on.views.home', name='home'),

    url(r'^supply/', include('supply.urls', namespace="supply")),

    url(r'^accounts/', include('accounts.urls', namespace="accounts")),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += staticfiles_urlpatterns()

supply/urls.py
from django.conf.urls import patterns, url
from supply import views

urlpatterns = patterns('supply.views',
    # ex: /supply/
    url(r'^$', 'index', name='index'),

    # ex: /supply/orders/new
    url(r'^orders/new/$', 'order_new', name='order_new'),
    # ex: /supply/orders/1/edit
    url(r'^orders/(?P<order_id>\d+)/edit/$', 'order_edit', name='order_edit'),
        
    # ex: /supply/lines
    url(r'^lines/$', 'lines', name='lines'),    
    # ex: /supply/lines/new/order/1
    url(r'^lines/new/order/(?P<order_id>\d+)/$', 'line_new', name='line_new'),
    # ex: /supply/lines/1/edit
    url(r'^lines/(?P<line_id>\d+)/edit/$', 'line_edit', name='line_edit'),

    # ex: /supply/inventory
    url(r'^inventory/$', 'inventory', name='inventory'),
    # ex: /supply/sites/new
    url(r'^sites/new/$', 'site_new', name='site_new'),
    # ex: /supply/sites/1/edit
    url(r'^sites/(?P<site_id>\d+)/edit/$', 'site_edit', name='site_edit'),
    
    # ex: /supply/adunits
    url(r'^adunits/$', 'adunits', name='adunits'),
    # ex: /supply/adunits/new/site/1
    url(r'^adunits/new/site/(?P<site_id>\d+)/$', 'adunit_new', name='adunit_new'),
    # ex: /supply/adunits/1/edit
    url(r'^adunits/(?P<adunit_id>\d+)/edit/$', 'adunit_edit', name='adunit_edit'),
    
    # ex: /supply/reports
    url(r'^reports/$', 'reports', name='reports'),
    # ex: /supply/reports/sites
    url(r'^reports/sites$', 'reports_sites', name='reports_sites'),
    # ex: /supply/reports/1
    url(r'^reports/(?P<report_id>\d+)/$', 'report_detail', name='report_detail'),

    # ex: /supply/error
    url(r'^error/(?P<type>\w+)/$', 'error', name='error'),
)

supply/forms.py
from django import forms
from supply.models import *

class site_form(forms.Form):
    site_name = forms.CharField(max_length=64)
    site_URL = forms.CharField(max_length=64)

 

supply/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django import forms
from supply.models import *
from accounts.models import UserProfile
from supply.forms import site_form
from django.db import models

from datetime import date, datetime, time, timedelta

def get_user_publisher(user):
    try:
        return user.userprofile.pub
    except UserProfile.DoesNotExist:
        return None

@login_required
def index(request):

    pub = get_user_publisher(request.user)
    if pub == None:
        return HttpResponseRedirect(reverse('accounts:error', kwargs={'type':'account'}))

    all_orders = Order.objects.filter(pub=pub)
    return render(request, "supply/index.html", {'order_collection': all_orders})

@login_required
def order_new(request):
    user = request.user
    pub = get_user_publisher(user)
    if pub == None:
        return HttpResponseRedirect(reverse('accounts:error', kwargs={'type':'account'}))
        
    class adUnit_by_site:
        site_with_adUnit = None
        entire_adUnit_list = []
      
    new_line_item= LineItem()
      
    errors = []
    adUnit_selected_list =[] #retrieved from POST
    
    adUnit_by_site_list = []  #generated for both GET and POST from database
        
    #field.choice lookup in template
    new_line_item= LineItem()
            
    current_site_list = Site.objects.filter(pub=pub)
    all_orders = Order.objects.filter(pub=pub)
    
    for item in current_site_list:
        element = adUnit_by_site()        
        if (len(AdUnit.objects.filter(site=item)) > 0):
            element.site_with_adUnit = item
            element.entire_adUnit_list = AdUnit.objects.filter(site=item)
            adUnit_by_site_list.append(element)
 
    if request.method == 'POST':   
        order_name_entry=request.POST.get('inputOrderName')
        order_company_entry=request.POST.get('inputCompany')
        line_name_entry = request.POST['inputLineName'] 
        line_platform_entry = request.POST['inputPlatform']
        line_type_entry = request.POST['type']
        
        if not order_name_entry:
            errors.append('inputOrderName')
        if not order_company_entry:
            errors.append('inputCompany') 
        if not line_name_entry:
            errors.append('Line Item Name')
        if not line_platform_entry:
            errors.append('Line Item Platform')        
        if not line_type_entry:
            errors.append('Line Item Type')
        
        inventory_queryDict = []
        
        inventory_queryDict = request.POST.getlist('inventory')
        if (len(inventory_queryDict) > 0 ):
            for id in inventory_queryDict:#received adunit.id from POST, convert to object
                adUnit_selected_list.append(AdUnit.objects.get(pk=id)) 
        else:
            errors.append('Inventory')
                     
        # create order 
        if ( len(errors) == 0 ):
                    
            order = Order()
            order.pub = pub 
            order.name = order_name_entry
            order.company= order_company_entry
            order.status = 'DFT'
            order.creator = user.username
             
        #create new line                                
            new_line_item.name = line_name_entry
            new_line_item.platform = line_platform_entry
            new_line_item.type = line_type_entry
            
            #non-mandatory attributes 
            new_line_item.status = 'DFT'            
            #hardcoded date/time for testing purposes
            new_line_item.start_date = str(date.today())
            new_line_item.start_time = str(datetime.now().time()).split('.')[0]
            new_line_item.end_date = str(date.today() + timedelta(days=30)) #run add for a month
            new_line_item.end_time = str(datetime.now().time()).split('.')[0]
            new_line_item.dlv_priority = 1

#database access
            order.save()  
                           
            if not order:            
                errors = 'failure saving new order'  
                return render(request, reverse('supply/order_new.html'), {'errors':str(errors), 'inputOrderName':order_name_entry, 'inputCompany':order_company_entry, 'inputLineName':line_name_entry, 'inputPlatform':line_platform_entry, 'type':line_type_entry, 'adUnit_by_site_list':adUnit_by_site_list, 'adUnit_selected_list':adUnit_selected_list,'line_item':new_line_item})

            new_line_item.order= order
                
            new_line_item.save() 

            if not new_line_item:
                errors = 'failure saving new line for order' 
                return render(request, 'supply/order_new.html', {'errors':str(errors), 'inputOrderName':order_name_entry, 'inputCompany':order_company_entry, 'inputLineName':line_name_entry, 'inputPlatform':line_platform_entry, 'type':line_type_entry, 'adUnit_by_site_list':adUnit_by_site_list, 'adUnit_selected_list':adUnit_selected_list, 'line_item':new_line_item})                                         

            for item in adUnit_selected_list: 
                new_line_item.adunits.add(item)
                                
            return HttpResponseRedirect(reverse('supply:index'))

        else: #invalid input
            return render(request, 'supply/order_new.html', { 'errors':str(errors), 'inputOrderName':order_name_entry, 'inputCompany':order_company_entry, 'inputLineName':line_name_entry, 'inputPlatform':line_platform_entry, 'type':line_type_entry, 'adUnit_by_site_list':adUnit_by_site_list, 'adUnit_selected_list':adUnit_selected_list,'line_item':new_line_item})

    else: # get request
        return render(request, 'supply/order_new.html', {'adUnit_by_site_list':adUnit_by_site_list,'line_item':new_line_item})       

@login_required
def order_edit(request, order_id):
    user_pub = get_user_publisher(request.user)
    if user_pub == None:
        return HttpResponseRedirect(reverse('accounts:error', kwargs={'type':'account'}))
        
    order_to_edit = Order.objects.get(id=order_id)
    if user_pub != order_to_edit.pub:
        return HttpResponseRedirect(reverse('supply:error', kwargs={'type':'permission'}))

    if request.method == 'POST':
        name_entry=request.POST.get('inputOrderName')
        company_entry=request.POST.get('inputCompany')
        	     
        if ( name_entry and company_entry):
            order_to_edit.name = name_entry
            order_to_edit.company= company_entry
                        
            order_to_edit.save();             
            return HttpResponseRedirect(reverse('supply:index'))
        else:
            err_invalid_new_order_input = 'Invalid order editing'  
            return render(request, 'supply/order_edit.html', {'errors':err_invalid_new_order_input, 'name':name_entry, 'company':company_entry})
    else:
        return render(request, 'supply/order_edit.html', {'id':order_id, 'name':order_to_edit.name, 'company':order_to_edit.company})       
    
@login_required
def lines(request):
    pub = get_user_publisher(request.user)
    if pub == None:
        return HttpResponseRedirect(reverse('accounts:error', kwargs={'type':'account'}))
        
    all_orders_with_line_items = []
    all_line_items =[]
    
    class all_lines_by_order:
        line_item_list = []
        order = None
        
    all_order_items = Order.objects.filter(pub=pub)
    for item in all_order_items:
        all_line_items +=  LineItem.objects.filter(order=item)
    
    for order in all_order_items:
        line_item_list = []
        
        for line_item in all_line_items:
            if line_item.order == order:
                line_item_list.append(line_item)
                
                #add order to order list if it has line items, and that it is the first line item
                if len(line_item_list) == 1:
                    one_combined_entry = all_lines_by_order()
                    one_combined_entry.order = order
                    
        if len(line_item_list) > 0:
          one_combined_entry.line_item_list = line_item_list                     
          all_orders_with_line_items.append(one_combined_entry)

    return render(request, "supply/lines.html", {'all_orders_with_line_items':all_orders_with_line_items})
    
@login_required
def line_new(request, order_id):
    pub = get_user_publisher(request.user)
    if pub == None:
        return HttpResponseRedirect(reverse('accounts:error', kwargs={'type':'account'}))

    current_order = Order.objects.get(id=order_id)

    if pub != current_order.pub:
        return HttpResponseRedirect(reverse('supply:error', kwargs={'type':'permission'}))

    errors = []
    adUnit_selected_list =[] #retrieved from POST
    
    adUnit_by_site_list = []  #generated for both GET and POST from database

    class adUnit_by_site:
        site_with_adUnit = None
        entire_adUnit_list = []
        
    #field.choice lookup in template
    new_line_item= LineItem()
    
    current_site_list = Site.objects.filter(pub=pub)
    
    for item in current_site_list:    
        element = adUnit_by_site()
        if (len(AdUnit.objects.filter(site=item)) > 0):#only add those sites with adUnits for display
            element.site_with_adUnit = item
            element.entire_adUnit_list = AdUnit.objects.filter(site=item)
            adUnit_by_site_list.append(element)      
   
    if request.method == 'POST':   
        
        name_entry = request.POST['inputLineName'] 
        platform_entry = request.POST['inputPlatform']
        type_entry = request.POST['type']
        
        if not name_entry:
            errors.append('Name')
        if not platform_entry:
            errors.append('Platform')        

supply/templates/supply/adunit_edit.html
<!---Inherits base.html --->
{% extends "supply/base.html" %}

<!---title block --->
{% block page_title %}
<title>New Site, Easy Native Ad Platform</title>
{% endblock %}

<!---Block for Navigation Bar on top of page --->
{% block nav_bar_block %}
	<ul class="nav navbar-nav">
            <li><a href="{% url 'supply:index' %}">Orders</a></li>
            <li class="active"><a href="{% url 'supply:inventory' %}">Inventory</a></li>
            <li><a href="{% url 'supply:reports' %}">Reports</a></li>
	</ul>
{% endblock %}

 <!---Block for menu list on left side --->   
{% block side_bar_block %}            
              <li><a href="{% url 'supply:inventory' %}">Sites</a></li>
              <li class="active"><a href="{% url 'supply:adunits' %}">AdUnits</a></li>
{% endblock %}

<!---Block for right pane --->            
{% block right_pane_block %} 
          <div class="panel panel-default table-responsive">
            <div class="panel-heading">
              <h3 class="panel-title">Edit ad unit</h3>
            </div>
            <div class="panel-body">                        
              <form class="form-horizontal" role="form" action="{% url 'supply:adunit_edit' adunit_id %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                  <label for="name" class="col-lg-2 control-label">Name</label>
                  <div class="col-lg-10">
                    <input type="text" class="form-control" name="name" placeholder="Sample AdUnit Name" value="{{ad_unit.name}}">
                  </div>
                </div>
                
                <div class="form-group">
                  <label for="type" class="col-lg-2 control-label">Type</label>
                  <div class="col-lg-10">
                    <select class="form-control" name="type" value="{{ad_unit.type}}">                    
                      {% for choice in ad_unit.AD_TYPES %}
                        <option value = "{{ choice.0 }}" > {{ choice.1 }} </option>
                      {% endfor %}
                    </select>
                  </div>
                </div>
                <div class="form-group">
                  <label for="type" class="col-lg-2 control-label">Target Window</label>
                  <div class="col-lg-10">
                    <select class="form-control" name="target" value="{{ad_unit.targetwindow}}">
                      {% for choice in ad_unit.TARGET_WINDOW %}
                        <option value = "{{ choice.0 }}" > {{ choice.1 }} </option>
                      {% endfor %}
                    </select>
                  </div>
                </div>
                <div class="form-group">
                  <label for="size" class="col-lg-2 control-label">Size</label>
                  <div class="col-lg-10">
                    <input type="text" class="form-control" name="size" value="{{ad_unit.sizes}}">
                  </div>
                </div>
                <div class="form-group">
                  <label for="desc" class="col-lg-2 control-label">Description</label>
                  <div class="col-lg-10">
                    <textarea class="form-control" rows="4" name="desc" placeholder="Ad unit for native in-stream ads" value="{{ad_unit.desc}}"></textarea>
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-lg-offset-2 col-lg-10">
                    <button type="submit" class="btn btn-default">Update</button>
                  </div>
                </div>
              </form>
            </div>            
            <div class="panel-footer">
            </div>
          </div><!--/panel-->
{% endblock %}

supply/templates/supply/adunit_new.html
<!---Inherits base.html --->
{% extends "supply/base.html" %}

<!---title block --->
{% block page_title %}
<title>New Site, Easy Native Ad Platform</title>
{% endblock %}

<!---Block for Navigation Bar on top of page --->
{% block nav_bar_block %}
	<ul class="nav navbar-nav">
            <li><a href="{% url 'supply:index' %}">Orders</a></li>
            <li class="active"><a href="{% url 'supply:inventory' %}">Inventory</a></li>
            <li><a href="{% url 'supply:reports' %}">Reports</a></li>
	</ul>
{% endblock %}

 <!---Block for menu list on left side --->   
{% block side_bar_block %}            
              <li><a href="{% url 'supply:inventory' %}">Sites</a></li>
              <li class="active"><a href="{% url 'supply:adunits' %}">AdUnits</a></li>
{% endblock %}

<!---Block for right pane --->            
{% block right_pane_block %} 
          <div class="panel panel-default table-responsive">
            <div class="panel-heading">
              <h3 class="panel-title">New Ad Unit</h3>
            </div>
            <div class="panel-body">                        
              <form class="form-horizontal" role="form" action="{% url 'supply:adunit_new' site_id %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                  <label for="name" class="col-lg-2 control-label">Name</label>
                  <div class="col-lg-10">
                    <input type="text" class="form-control" name="name" placeholder="AdUnit Name">
                  </div>
                </div>
                <div class="form-group">
                  <label for="type" class="col-lg-2 control-label">Type</label>
                  <div class="col-lg-10">
                    <select class="form-control" name="type">                    
                      {% for choice in ad_unit.AD_TYPES %}
                        <option value = "{{ choice.0 }}" > {{ choice.1 }} </option>
                      {% endfor %}
                    </select>
                  </div>
                </div>
                <div class="form-group">
                  <label for="type" class="col-lg-2 control-label">Target Window</label>
                  <div class="col-lg-10">
                    <select class="form-control" name="target">
                      {% for choice in ad_unit.TARGET_WINDOW %}
                        <option value = "{{ choice.0 }}" > {{ choice.1 }} </option>
                      {% endfor %}
                    </select>
                  </div>
                </div>
                <div class="form-group">
                  <label for="size" class="col-lg-2 control-label">Size</label>
                  <div class="col-lg-10">
                    <input type="text" class="form-control" name="size" placeholder="AdUnit Size">
                  </div>
                </div>
                <div class="form-group">
                  <label for="desc" class="col-lg-2 control-label">Description</label>
                  <div class="col-lg-10">
                    <textarea class="form-control" rows="4" name="desc" placeholder="Description"></textarea>
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-lg-offset-2 col-lg-10">
                    <button type="submit" class="btn btn-default">Save</button>
                  </div>
                </div>
              </form>
            </div>            
            <div class="panel-footer">
            </div>
          </div><!--/panel-->
{% endblock %}

supply/templates/supply/index.html
<!---Inherits base.html --->
{% extends "supply/base.html" %}

<!---title block --->
{% block page_title %}
<title>Easy Native Ad Platform</title>
{% endblock %}

<!---Block for Navigation Bar on top of page --->
{% block nav_bar_block %}
	<ul class="nav navbar-nav">
		<li class="active"><a href="{% url 'supply:index' %}">Orders</a></li>
		<li><a href="{% url 'supply:inventory' %}">Inventory</a></li>
		<li><a href="{% url 'supply:reports' %}">Reports</a></li>
	</ul>
{% endblock %}

 <!---Block for menu list on left side --->   
{% block side_bar_block %}            
	<li class="active"><a href="{% url 'supply:index' %}">Orders</a></li>
	<li><a href="{% url 'supply:lines' %}">Line Items</a></li>
{% endblock %}

<!---Block for right pane --->            
{% block right_pane_block %} 
	<div class="panel panel-default table-responsive">
    	<div class="panel-heading">
        	<h3 class="panel-title">Orders</h3>
        </div>
        <div class="panel-body"> 
        	<form action="{% url 'supply:order_new' %}">                       
        		<button type="submit" class="btn btn-default">New Order</button>
        	</form>              
        </div>  
		<div class="table-responsive">                     
        	<table class="table">         
                <tr>
                  <th>Name</th><th>Line Items</th><th>Advertiser</th><th>Start Time</th><th>End Time</th>
                </tr>
                {% for order_entry in order_collection %}       
                <tr>
					<td><a href="{% url 'supply:order_edit' order_entry.id %}">{{order_entry.name}}</a></td><td>{{order_entry.status}}</td><td>{{order_entry.company}}</td><td>Sep 1, 2013 12:00pm</td><td>Sep 30, 2013, 11:59pm</td>
				</tr>
				{% endfor %}
				</table> 
		</div>           
		<div class="panel-footer">
	</div>
</div><!--/panel-->
{% endblock %}

supply/templates/supply/line_edit.html
<!---Inherits base.html --->
{% extends "supply/base.html" %}

<!---title block --->
{% block page_title %}
<title>New Order, Easy Native Ad Platform</title>
{% endblock %}

<!---Block for Navigation Bar on top of page --->
{% block nav_bar_block %}
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'supply:index' %}">Orders</a></li>
            <li><a href="{% url 'supply:inventory' %}">Inventory</a></li>
            <li><a href="{% url 'supply:reports' %}">Reports</a></li>
          </ul>
{% endblock %}

 <!---Block for menu list on left side --->
{% block side_bar_block %}
              <li><a href="{% url 'supply:index' %}">Orders</a></li>
              <li class="active"><a href="{% url 'supply:lines' %}">Line Items</a></li>
{% endblock %}

<!---Block for right pane --->
{% block right_pane_block %}
          <form class="form-horizontal" role="form" action="{% url 'supply:line_edit' line_id %}" method="post">
            {% csrf_token %}

            <div class="panel panel-default table-responsive">
              <div class="panel-heading">
                <h3 class="panel-title">Edit line item</h3>
              </div><!--/panel-head-->
              <div class="panel-body">                        
                <div class="form-group">
                  <label for="inputLineName" class="col-lg-2 control-label">Name</label>
                  <div class="col-lg-10">
                    <input type="text" class="form-control" name="inputLineName" value="{{inputLineName}}"> 
                  </div>
                </div>
                
                <div class="form-group">
                  <label for="inputPlatform" class="col-lg-2 control-label">Platform</label>
                  <div class="col-lg-10", id="inputPlatform">
                    <select class="form-control" name="inputPlatform">
                      {% for choice in line_item.PLATFORM_TYPES %}
                        {% ifequal inputPlatform choice.0 %}
                          <option value = "{{ choice.0 }}" selected > {{ choice.1 }} </option>
                        {% else %}  
                          <option value = "{{ choice.0 }}"> {{ choice.1 }} </option>
                        {% endifequal %}
                      {% endfor %}
                    </select>
                  </div>
                </div>

                <label class="control-label">Settings</label>
                <div class="form-group">
                  <label for="type" class="col-lg-2 control-label">Type</label>
                  <div class="col-lg-10">
                    <select class="form-control" name="type">
                      {% for choice in line_item.LINE_ITEM_TYPES %}
                        {% ifequal type choice.0 %}
                          <option value = "{{ choice.0 }}" selected > {{ choice.1 }} </option>
                        {% else %}  
                          <option value = "{{ choice.0 }}"> {{ choice.1 }} </option>
                        {% endifequal %}
                      {% endfor %}
                    </select>
                  </div>
                </div>

                <label class="control-label">Targeting</label>
                <div class="form-group">
                  <label for="inventory" class="col-lg-2 control-label">Inventory</label>
                  <div class="col-lg-10">
                    {% for element_2 in adUnit_by_site_list %}
                    <label class="control-label">{{ element_2.site_with_adUnit }}</label>
                     {% for element_1 in element_2.entire_adUnit_list %}
                        <label class="checkbox">
                          {% if element_1.selected %}
                            <input type="checkbox" name="inventory" value="{{element_1.adUnit.id}}" checked >{{element_1.adUnit.name}} 
                          {% else %}
                            <input type="checkbox" name="inventory" value="{{element_1.adUnit.id}}">{{element_1.adUnit.name}}                      
                          {% endif %}
                        </label>
                      {% endfor %} <!--adUnit---> 
                         
                    {% endfor %} <!--element --->
                  </div>
                </div>



              </div><!--/panel-body-->

              <div class="panel-footer">
                <div class="form-group">
                  <div class="col-lg-offset-2 col-lg-10">
                    <button type="submit" class="btn btn-default">Update</button>
                  </div>
                </div>
              </div><!--/panel-footer-->

            </div><!--/panel-->
          </form>
{% endblock %}

supply/templates/supply/order_edit.html
<!---Inherits base.html --->
{% extends "supply/base.html" %}

<!---title block --->
{% block page_title %}
    <title>Easy Native Ad Platform</title>
{% endblock %}

<!---Block for Navigation Bar on top of page --->
{% block nav_bar_block %}
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'supply:index' %}">Orders</a></li>
            <li><a href="{% url 'supply:inventory' %}">Inventory</a></li>
            <li><a href="{% url 'supply:reports' %}">Reports</a></li>
          </ul>
{% endblock %}

 <!---Block for menu list on left side --->
{% block side_bar_block %}
              <li class="active"><a href="{% url 'supply:index' %}">Orders</a></li>
              <li><a href="{% url 'supply:lines' %}">Line Items</a></li>
{% endblock %}

<!---Block for right pane --->
{% block right_pane_block %}

          <div class="panel panel-default table-responsive">
            <div class="panel-heading">
              <h3 class="panel-title">Edit order</h3>
            </div>
            <div class="panel-body">                        
              <form class="form-horizontal" role="form" action="{% url 'supply:order_edit' id %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                  <label for="inputOrderName" class="col-lg-2 control-label">Order Name</label>
                  <div class="col-lg-10">
                    <input type="text" class="form-control" name="inputOrderName" value="{{ name }}">
                  </div>
                </div>
                <div class="form-group">
                  <label for="inputCompany" class="col-lg-2 control-label">Company</label>
                  <div class="col-lg-10">
                    <input type="text" class="form-control" name="inputCompany" value="{{ company }}">
                  </div>
                </div>
    
                <div class="form-group">
                  <div class="col-lg-offset-2 col-lg-10">
                    <button type="submit" class="btn btn-default">Update</button>
                  </div>
                </div>
              </form>
            </div>            
            <div class="panel-footer">
            </div>
          </div><!--/panel-->
{% endblock %}

supply/templates/supply/order_new.html
<!---Inherits line_new_base.html, in order to put both new order and new lines in one page --->
{% extends "supply/line_new_base.html" %}

<!---title block --->
{% block page_title %}
<title>New Order, Easy Native Ad Platform</title>
{% endblock %}

<!---Block for Navigation Bar on top of page --->
{% block nav_bar_block %}
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'supply:index' %}">Orders</a></li>
            <li><a href="{% url 'supply:inventory' %}">Inventory</a></li>
            <li><a href="{% url 'supply:reports' %}">Reports</a></li>
          </ul>
{% endblock %}

 <!---Block for menu list on left side --->   
{% block side_bar_block %}            
              <li class="active"><a href="{% url 'supply:index' %}">Orders</a></li>
              <li><a href="{% url 'supply:lines' %}">Line Items</a></li>
{% endblock %}

<!---Block for right pane --->            

    
    <form class="form-horizontal" role="form" 
    {% block form_action %}
      action="{% url 'supply:order_new' %}" method="post">         
    {% endblock form_action %}
{% block err_msg %}
	{% if errors %}
      <p style="color: red">
        Invalid input for new order: {{errors}}
       </p>
    {% endif %}
{% endblock err_msg %}                          
            {% block template_rendering_1 %}
            <div class="panel panel-default table-responsive">         
               <div class="panel-heading">
                 <h3 class="panel-title">New order</h3>
               </div><!--/panel-head-->             
               <div class="panel-body">   
                                  
                <div class="form-group">
                  <label for="inputOrderName" class="col-lg-2 control-label">Name</label>
                  <div class="col-lg-10">
                    <input type="text" class="form-control" name="inputOrderName" placeholder="Name" value="{{name }}">
                 </div>
                </div>
                <div class="form-group">
                  <label for="inputCompany" class="col-lg-2 control-label">Company</label>
                  <div class="col-lg-10">
                    <input type="text" class="form-control" name="inputCompany" placeholder="Company" value="{{ company }}">
                 </div>
                </div>
                
              </div><!--/panel-body-->
                  
              <div class="panel-footer">

              </div><!--/panel-footer-->

            </div><!--/panel-->
                {% endblock template_rendering_1 %}