accounts/urls.py
from django.conf.urls import patterns, url, include
from supply import views
from django.contrib.auth import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin

urlpatterns = patterns('accounts.views',
    # ex: /accounts/
    #url(r'^$', 'index', name='index'),
    # ex: /accounts/signin
    url(r'^signin/$', 'signin', name='signin'),
    # ex: /accounts/signin
    url(r'^signedout/$', 'signedout', name='signedout'),
    # ex: /accounts/signup
    url(r'^signup/$', 'signup', name='signup'),
    # ex: /accounts/signup_done
    url(r'^signup_done/$', 'signup_done', name='signup_done'),
    # ex: /accounts/reset
    url(r'^reset/$', 'reset', name='reset'),
    # ex: /accounts/password_sent
#    url(r'^reset_password_sent/$', 'django.contrib.auth.views.password_reset_done'),
    # ex: /accounts/reset_password_confirm
    url(r'reset_confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 'reset_confirm', name='reset_confirm'),
    # ex: /accounts/reset_password_complete
#    url(r'^reset_password_complete/$', 'django.contrib.auth.views.password_reset_complete'),

    # ex: /accounts/error
    url(r'^error/(?P<type>\w+)/$', 'error', name='error'),

    #user name autocomplete URL, /accounts/signup/lookup
    url(r'^signup/lookup', 'username_lookup'),
    #end user name autocomplete
    # ex: /accounts/account_recovery
    #url(r'^account_recovery/$', 'account_recovery', name='account_recovery'),
    # ex: /accounts/account_recovery_confirmation
    #url(r'^account_recovery_confirmation/$', 'account_recovery_confirmation', name='account_recovery_confirmation'),


    #Don't remove, this is important!
    #url(r'^account/', include('django.contrib.auth.urls')),
    #this is the accounts app main url
    #url(r'^accounts/', include('accounts.urls', namespace="accounts"))
)
# add password recovery views
#urlpatterns += patterns('accounts.views', url(r'^forgot_password/$', 'forgot_password', name="forgot_password" ),)

#this is the url for password reset authentication
#urlpatterns += patterns('',
    # ex: /accounts/reset_password_request
#    url(r'^reset_password_request/$', 'django.contrib.auth.views.password_reset'),
    # ex: /accounts/password_sent
#    url(r'^reset_password_sent/$', 'django.contrib.auth.views.password_reset_done'),
    # ex: /accounts/reset_password_confirm
#    url(r'reset_password_confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm'),
    # ex: /accounts/reset_password_complete
#    url(r'^reset_password_complete/$', 'django.contrib.auth.views.password_reset_complete'),

#)

on/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    #url(r'^$', 'on.views.home', name='home'),

    url(r'^supply/', include('supply.urls', namespace="supply")),

    url(r'^accounts/', include('accounts.urls', namespace="accounts")),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += staticfiles_urlpatterns()

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from supply.models import Publisher

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    phone = models.CharField(max_length=32, blank=True)
    title = models.CharField(max_length=32, blank=True)
    pub = models.ForeignKey(Publisher, blank=True, null=True)
    def __unicode__(self):
        return self.user.username

accounts/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import * 
from django.utils.html import strip_tags
from django.db import IntegrityError
from django import forms
from supply.models import Publisher
from accounts.models import UserProfile
from django.contrib.auth.views import password_reset, password_reset_confirm

#for user name autocomplete
from django.utils import simplejson
#end user name autocomplete

class FormErrors:
    pass

class SignupForm(forms.Form):
    username = forms.CharField(max_length=30)
    email = forms.CharField(max_length=75)
    password = forms.CharField(max_length=60)
    password_confirm = forms.CharField(max_length=60)
    firstname = forms.CharField(max_length=30, required=False)
    lastname = forms.CharField(max_length=30)
    companyname = forms.CharField(max_length=64)
    phone = forms.CharField(max_length=32)
    address = forms.CharField(max_length=64, required=False)
    address2 = forms.CharField(max_length=64, required=False)
    city = forms.CharField(max_length=32, required=False)
    state = forms.CharField(max_length=32, required=False)
    zipcode = forms.CharField(max_length=32, required=False)
    province = forms.CharField(max_length=64, required=False)
    country = forms.CharField(max_length=64, required=False)

def signin(request):
    logout(request)
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('supply:index'))
            else:
                # Return a 'disabled account' error message
                return render(request, "accounts/signin.html", {'error': 'Disabled account, please re-activate the account, or use a different account'})
        else:
            # Return an 'invalid login' error message.
            return render(request, "accounts/signin.html", {'error': 'Username/email and password do not match'})
    else:
        return render(request, "accounts/signin.html", {})

def signedout(request):
    logout(request)
    msg = 'You have successfully signed out.'
    return render(request, "accounts/signedout.html", {'msg':msg})

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        # form will validate basic rules
        if not form.is_valid():
            return render(request, "accounts/signup.html", {'form' : form, })

        # we also need to validate advanced rules here
        errors = FormErrors()
        has_error = False

        username = form.cleaned_data['username']
        email = form.cleaned_data['email']
        password = form.cleaned_data['password']
        password_confirm = form.cleaned_data['password_confirm']

        if len(password) < 8:
            errors.password = "Password too short"
            has_error = True
        elif re.search(r'\d', password) == None:
            errors.password = "Password must contain at least 1 number"
            has_error = True
        elif re.search(r'[A-Z]', password) == None:
            errors.password = "Password must contain at least 1 upper case letter"
            has_error = True
        elif re.search(r'[a-z]', password) == None:
            errors.password = "Password must contain at least 1 lower case letter"
            has_error = True

        if password_confirm != password:
            errors.password_confirm = "Passwords do not match"
            has_error = True

        if has_error:
            return render(request, "accounts/signup.html", {'form' : form, 'errors' : errors, })

        # save user info
        try:
            user = User.objects.create_user(username, email, password)
        except IntegrityError:
            errors.username = "This username is already in use, please pick a different username"
            return render(request, "accounts/signup.html", {'form' : form, 'errors' : errors, })

        user.first_name = request.POST['firstname']
        user.last_name = form.cleaned_data['lastname']
        try:
            user.save()
        except IntegrityError:
            errors.username = "This username is already in use, please pick a different username"
            return render(request, "accounts/signup.html", {'form' : form, 'errors' : errors, })

        pub = Publisher()
        pub.name = form.cleaned_data['companyname']
        pub.phone = form.cleaned_data['phone']
        pub.address = form.cleaned_data['address']
        pub.address2 = form.cleaned_data['address2']
        pub.city = form.cleaned_data['city']
        pub.state = form.cleaned_data['state']
        pub.province = form.cleaned_data['province']
        pub.zipcode = form.cleaned_data['zipcode']
        pub.country = form.cleaned_data['country']
        try:
            pub.save()
        except IntegrityError:
            errors.companyname = "This company name is already in use, please use a different company name, or contact us to claim your company name"
            return render(request, "accounts/signup.html", {'form' : form, 'errors' : errors, })

        profile = UserProfile()
        profile.user = user;
        profile.pub = pub;
        profile.save()

        # tell user he's signed up and ask him to sign in
        return HttpResponseRedirect(reverse('accounts:signup_done'))
    else:
        return render(request, "accounts/signup.html", {})

def signup_done(request):
    return render(request, "accounts/signup_done.html", {})

def error(request, type):
    errors = { "account" : { "title":"Account Error", 
                             "msg":"Your account has no publisher information, please set up your publisher account before proceeding" },
             }
    try:
        error = errors[type]
    except KeyError:
        error = { "title":"Account Error",
                  "msg":"Error in your account." }
    return render(request, "accounts/error.html", {"error" : error })

#not tested due to email server
def reset_confirm(request, uidb36=None, token=None):
    return password_reset_confirm(request, template_name='accounts/reset_confirm.html',
        uidb36=uidb36, token=token, post_reset_redirect=reverse('accounts:signin'))

#not tested due to email server
def reset(request):
    return password_reset(request, template_name='accounts/reset_form.html',
        email_template_name='accounts/reset_email.html',
        subject_template_name='accounts/reset_subject.txt',
        post_reset_redirect=reverse('accounts:signin'))

#user name auto complete

def username_lookup(request):
    # Default return list
    results = []
    if request.method == "GET":
        if request.GET.has_key(u'term'):
            value = request.GET[u'term']

            # Ignore queries shorter than length 3
            if len(value) >= 2:
                model_results = User.objects.filter(username=value)
                for x in model_results:
                  results.append(x.username)
    json = simplejson.dumps(results)
    return HttpResponse(json, content_type='application/json')
#end user name auto complete

accounts/templates/accounts/error.html
<!---Inherits frame.html --->
{% extends "accounts/frame.html" %}

{% load staticfiles %}

<!---title block --->
{% block page_title %}
  <title>Error - Open Native</title>
{% endblock %}

  {% block page_file_links %}
    <!-- Custom styles for this template -->
    <link href="{% static 'accounts/css/signin.css' %}" rel="stylesheet">
  {% endblock %}

  <!---Block for Navigation Bar on top of page --->
  {% block nav_bar_block %}
  {% endblock %}

  {% block main_row_block %}
    <div class="container">

      <div class="jumbotron">
        <h3>{{error.title}}</h3>
        <p>{{error.msg}}</p>
        <p>
          <a class="btn btn-lg btn-primary" href="{% url 'accounts:signin' %}">Sign out &raquo;</a>
        </p>
      </div>

    </div> <!-- /container -->

  {% endblock %}

accounts/templates/accounts/frame.html
<!DOCTYPE html> {% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="{% static 'bootstrap-3.0.0/assets/ico/favicon.png' %}">
    
    <!---title block --->
    {% block page_title %}
    <title>Open Native</title>
    {% endblock %}

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap-3.0.0/dist/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom files for this template -->
    {% block page_file_links %}
    {% endblock %}

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="{% static 'bootstrap-3.0.0/assets/js/html5shiv.js' %}"></script>
      <script src="{% static 'bootstrap-3.0.0/assets/js/respond.min.js' %}"></script>
    <![endif]-->
  </head>

  <body>

    <div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Open Native</a>
        </div>
        <div class="collapse navbar-collapse">
        <!---Block for Navigation Bar on top of page --->
        {% block nav_bar_block %}
        {% endblock %}
        {% block nav_bar_right_block %}
          <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
            <li><a href="#">{{ user.get_username }}</a></li>
            <li><a href="{% url 'accounts:signedout' %}">Sign out</a></li>
          {% else %}
            <li><a href="{% url 'accounts:signin' %}">Sign in</a></li>
            <li><a href="{% url 'accounts:signup' %}">Sign up</a></li>
          {% endif %}
          </ul>
        {% endblock %}
        </div><!-- /.nav-collapse -->
      </div><!-- /.container -->
    </div><!-- /.navbar -->

    <!-- Main row block - between header and footer -->
    {% block main_row_block %}
    {% endblock %}

    <div class="container">
      <hr>
      <footer>
        <p>&copy; Company 2013</p>
      </footer>
    </div><!--/.container-->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'bootstrap-3.0.0/assets/js/jquery.js' %}"></script>
    <script src="{% static 'bootstrap-3.0.0/dist/js/bootstrap.min.js' %}"></script>
    <!---Block for page end file links --->
    {% block page_end_file_links %}
    {% endblock %}

  </body>
</html>

accounts/templates/accounts/reset_confirm.html
#password_reset_confirm.html


<!---Inherits frame.html --->
{% extends "accounts/frame.html" %}

{% load staticfiles %}

<!---title block --->
{% block page_title %}
  <title>Password Reset Confirmation- Open Native</title>
{% endblock %}

  <!---Block for Navigation Bar on top of page --->
  {% block nav_bar_block %}
  {% endblock %}

  {% block main_row_block %}
    <div class="container">

      <div class="jumbotron">
        <h4>Reset Password:</h4> 
           
           
           {% if validlink %}
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Submit</button>
        </form>
    {% else %}
        <p>This reset link is no longer valid!</p>
    {% endif %}
      </div>
    </div> <!-- /container -->
  {% endblock %}

accounts/templates/accounts/reset_email.html
#password_reset_email.html

<!---Inherits frame.html --->
{% extends "accounts/frame.html" %}

{% load staticfiles %}

<!---title block --->
{% block page_title %}
  <title>Password Reset Email - Open Native</title>
{% endblock %}

  <!---Block for Navigation Bar on top of page --->
  {% block nav_bar_block %}
  {% endblock %}

  {% block main_row_block %}
    <div class="container">

      <div class="jumbotron">
           
        {% block email_text %}
        You're receiving this e-mail because you requested 
        a password reset for your user account at {{ site_name }}, with email {{ email }}.
        
        Follow the link below to reset your password:
         {{ protocol}}://{{ domain }}{% url 'accounts:reset_confirm' uidb36=uid token=token %}
         
        <p>Your username, in case you've forgotten: {{ user.username }}

         Thanks for using our site! </p>
        {% endblock email_text %}                
      </div>
    </div> <!-- /container -->
  {% endblock %}

accounts/templates/accounts/reset_form.html
#password_reset_form.html
<!---Inherits frame.html --->
{% extends "accounts/frame.html" %}

{% load staticfiles %}

<!---title block --->
{% block page_title %}
  <title>Password Reset - Open Native</title>
{% endblock %}

  <!---Block for Navigation Bar on top of page --->
  {% block nav_bar_block %}
  {% endblock %}

  {% block main_row_block %}
    <div class="container">

      <div class="jumbotron">
        <h4>Reset Password</h4> 
           
          <p>Forgotten your password? 
             Enter your e-mail address below, 
             and we'll e-mail instructions for setting a new one.</p>
                
          <form action="" method="post">
            {% csrf_token %}
            {% if form.email.errors %}
            <div class="message red-gradient">{{ form.email.errors }}</div><br/>
            {% endif %}  
            <p>E-mail address: {{ form.email }} <br/><br/>
            <input type="submit" value="Reset my password"></p>
            </form>
      </div>
    </div> <!-- /container -->
  {% endblock %}

accounts/templates/accounts/signedout.html
<!---Inherits frame.html --->
{% extends "accounts/frame.html" %}

{% load staticfiles %}

<!---title block --->
{% block page_title %}
  <title>Signed Out - Open Native</title>
{% endblock %}

  {% block page_file_links %}
    <!-- Custom styles for this template -->
    <link href="{% static 'accounts/css/signin.css' %}" rel="stylesheet">
  {% endblock %}

  <!---Block for Navigation Bar on top of page --->
  {% block nav_bar_block %}
  {% endblock %}

  {% block main_row_block %}
    <div class="container">
     <h1>  </h1>
      <div class="jumbotron">
        <p>{{msg}}</p>
        <p>
          <a class="btn btn-lg btn-primary" href="{% url 'accounts:signin' %}">Sign back in... &raquo;</a>
        </p>
      </div>

    </div> <!-- /container -->

  {% endblock %}

accounts/templates/accounts/signin.html
<!---Inherits frame.html --->
{% extends "accounts/frame.html" %}

{% load staticfiles %}

<!---title block --->
{% block page_title %}
  <title>Sign In - Open Native</title>
{% endblock %}

  {% block page_file_links %}
    <!-- Custom styles for this template -->
    <link href="{% static 'accounts/css/signin.css' %}" rel="stylesheet">
  {% endblock %}

  <!---Block for Navigation Bar on top of page --->
  {% block nav_bar_right_block %}
          <ul class="nav navbar-nav navbar-right">
            <li class="active"><a href="{% url 'accounts:signin' %}">Sign in</a></li>
            <li><a href="{% url 'accounts:signup' %}">Sign up</a></li>
          </ul>
  {% endblock %}

  {% block main_row_block %}
    <div class="container">

      <form class="form-signin" action=""  method="POST">
        {% csrf_token %}
        <h2 class="form-signin-heading">Please sign in</h2>
        {% if error %}
            <p style="color: red;">
                {{error}}
            </p>
        {% endif %}
        <input type="text" class="form-control" name="username" placeholder="Username or Email" autofocus>
        <input type="password" class="form-control" name="password" placeholder="Password">
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
        <div class="form-signin">
        <p>
        <a href={% url 'accounts:reset' %}>Forgot password?</a>
        </p>
        <p>
        <a href="{% url 'accounts:signup' %}">Need an account? Sign up now.</a>
        </p>
        </div>
      </form>
      
    </div> <!-- /container -->

  {% endblock %}

accounts/templates/accounts/signup_done.html
<!---Inherits frame.html --->
{% extends "accounts/frame.html" %}

{% load staticfiles %}

<!---title block --->
{% block page_title %}
  <title>Sign Up Completed - Open Native</title>
{% endblock %}

  {% block page_file_links %}
    <!-- Custom styles for this template -->
    <link href="{% static 'accounts/css/signin.css' %}" rel="stylesheet">
  {% endblock %}

  <!---Block for Navigation Bar on top of page --->
  {% block nav_bar_block %}
  {% endblock %}

  {% block main_row_block %}
    <div class="container">

      <div class="jumbotron">
        <h3>Welcome to Open Native</h3>
        <p>You have signed up to Open Native. Please proceed to sign in:</p>
        <p>
          <a class="btn btn-lg btn-primary" href="{% url 'accounts:signin' %}">Sign in &raquo;</a>
        </p>
      </div>

    </div> <!-- /container -->

  {% endblock %}